name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    name: Verify PR
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.8.17
      - run: npm ci
      - run: npx nx affected --target=lint --base=master --parallel
      - run: npx nx affected --target=test --base=master --parallel
      - run: npx nx affected --target=build --base=master --parallel
