name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'ture'
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  main:
    runs-on: ubuntu-latest
    name: Verify PR
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1.8.17
      - run: npm ci
      - run: npx nx affected --target=lint --base=origin/master --parallel
      - run: npx nx affected --target=test --base=origin/master --parallel
      - run: npx nx affected --target=build --base=origin/master --parallel
      - run: npx @nrwl/nx-cloud stop-all-agents

  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.8.17
      - run: npx @nrwl/nx-cloud start-agent
